config/routes.rb
Blog::Application.routes.draw do

	root to: "welcome#index"

	resources :posts do
		resources :comments
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post

	validates :commenter,
		presence: true

	validates :body,
		presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	validates :title,
		presence: true,
		length: { minimum: 5 }

	validates :text,
		presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin.123", only: :destroy

	def create
		@post = Post.find( params[:post_id] )
		@comment = @post.comments.create( params[:comment].permit(:commenter, :body) )
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find( params[:post_id] )
		@comment = @post.comments.find( params[:id] )
		@comment.destroy
		redirect_to post_path(@post)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin.123", except: [:index, :show]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :text))

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :text))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :text)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<%
#### Partial for each comment.
 %>

<li class="comment list-group-item">
	<%= link_to( [comment.post, comment], title: "Delete", class: "btn btn-default btn-sm pull-right", method: :delete, data: { confirm: "Do you want to delete this comment?" } ) do %>
		<span class="glyphicon glyphicon-trash"></span>
	<% end %>

	<p>
		<strong><%= comment.commenter %></strong>
	</p>

	<p>
		<%= comment.body %>
	</p>
</li>

app/views/comments/_form.html.erb
<%
#### Comment form.
 %>

<%= form_for( [@post, @post.comments.build] ) do |f| %>
	<div class="form-group">
		<%= f.label :commenter %>
		<%= f.text_field :commenter, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, rows: "5", class: "form-control" %>
	</div>
	<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


		<nav class="navbar navbar-default navbar-static-top" role="navigation">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">

						<div class="navbar-header">
						<%= link_to "Test Blog", { controller: "welcome" },  class: "navbar-brand" %>
						</div>

						<ul class="nav navbar-nav">
							<li><%= link_to "Blog", controller: "posts" %></li>
						</ul>

					</div> <!-- col8 -->
				</div> <!-- row -->
			</div> <!-- container -->
		</nav> <!-- navbar-top -->

	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">

				<%= yield %>

			</div> <!-- col8 -->
		</div> <!-- row -->
	</div> <!-- container -->

</body>
</html>

app/views/posts/_form.html.erb
<%
#### Form for adding & editing posts.
 %>

<%= form_for @post do |f|  %>

	<% # Check if we are returning with an error.
	   # If so, display error message.
	%>
	<% if @post.errors.any? %>
		<div class="alert alert-danger">

			<p><strong><%= pluralize( @post.errors.count, "error" ) %> prohibited this post from being saved:</strong></p>

			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>

		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :title  %>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :text %>
		<%= f.text_area :text, rows: "10", class: "form-control" %>
	</div>

	<p>
		<%= f.submit class: "btn btn-default btn-lg" %>
	</p>

<% end %>

app/views/posts/edit.html.erb
<%
#### Edit and existing post.
 %>

<h1>Edit > <%= @post.title %></h1>

<p>
	<%= link_to(posts_path, class: "btn btn-default btn-sm") do %>
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back to All Posts
	<% end %>
</p>

<%= render 'form' %>

app/views/posts/index.html.erb
<%
#### List all posts.
 %>

<h1>All Posts</h1>

<%= link_to(new_post_path, class: "btn btn-default btn-sm") do %>
	<span class="glyphicon glyphicon-plus-sign"></span> New Post
<% end %>

<hr>


	<% @posts.each do |post| %>
		<p class="btn-group pull-right">
				<%= link_to( post, title: "View", class: "btn btn-default btn-sm" ) do %>
					<span class="glyphicon glyphicon-eye-open"></span>
				<% end %>

				<%= link_to( edit_post_path(post), title: "Edit", class: "btn btn-default btn-sm" ) do %>
					<span class="glyphicon glyphicon-cog"></span>
				<% end %>

				<%= link_to( post_path(post), title: "Delete", class: "btn btn-default btn-sm", method: :delete, data: { confirm: "Do you want to delete this post?" } ) do %>
					<span class="glyphicon glyphicon-trash"></span>
				<% end %>
		</p> <!-- btn-group -->

		<h2><%= link_to post.title, post %></h2>

		<p><%= truncate( post.text, length: 200 ) %></p>

		<hr>

	<% end %>

app/views/posts/new.html.erb
<%
#### Create new posts.
 %>

<h1>New Post</h1>

<p>
	<%= link_to(posts_path, class: "btn btn-default btn-sm") do %>
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back to All Posts
	<% end %>
</p>

<%= render 'form' %>

app/views/posts/show.html.erb
<%
#### Show a single post.
 %>

<p class="btn-group">
	<%= link_to(posts_path, class: "btn btn-default btn-sm") do %>
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back to All Posts
	<% end %>
	<%= link_to(edit_post_path(@post), title: "Edit", class: "btn btn-default btn-sm") do %>
		<span class="glyphicon glyphicon-cog"></span>
	<% end %>
</p>

<h1><%= @post.title %></h1>

<p>
	<%= @post.text %>
</p>

<hr>

<span class="badge pull-right"><%= @post.comments.count %></span>
<h2>Comments</h2>

<ul class="comments list-group">
	<%= render @post.comments %>
</ul>

<h3>Add a Comment</h3>
<%= render "comments/form" %>

app/views/welcome/index.html.erb
<h1>Hello World &amp; Welcome!</h1>

<p>This is the home page.</p>